"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from kombu import Queue

BACKEND_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BACKEND_DIR.parent

# Prefer the repo-level .env so existing local and deploy setups keep working.
load_dotenv(REPO_ROOT / ".env")
load_dotenv(BACKEND_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    return int(value)


def env_path(name, default, base_dir=REPO_ROOT):
    value = os.getenv(name)
    if not value:
        return default

    path = Path(value)
    if path.is_absolute():
        return path

    return base_dir / path


# Build paths inside the backend app like this: BASE_DIR / 'subdir'.
BASE_DIR = BACKEND_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DEBUG=False.")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["127.0.0.1", "localhost"])
LOCAL_DEV_TRUSTED_ORIGINS = [
    f"http://{host}:{port}"
    for port in (4173, 4174, 5173, 5174)
    for host in ("127.0.0.1", "localhost")
]
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    LOCAL_DEV_TRUSTED_ORIGINS,
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "django_filters",
    # Local apps
    "apps.content",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.content.performance_monitoring.PerformanceMonitoringMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DATABASE", "blog"),
        "USER": os.getenv("MYSQL_USER", "blog"),
        "PASSWORD": os.getenv("MYSQL_PASSWORD", ""),
        "HOST": os.getenv("MYSQL_HOST", "localhost"),
        "PORT": os.getenv("MYSQL_PORT", "3307"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/1",
        'KEY_PREFIX': 'blog',
        'TIMEOUT': 300,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = env_path("MEDIA_ROOT", REPO_ROOT / "media")

# R2 (S3-compatible) storage configuration
R2_ENABLED = env_bool("R2_ENABLED", False)
if R2_ENABLED:
    INSTALLED_APPS += ["storages"]

    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    AWS_S3_ADDRESSING_STYLE = os.getenv("AWS_S3_ADDRESSING_STYLE", "virtual")
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = None
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery Configuration
CELERY_BROKER_URL = f"amqp://{os.getenv('RABBITMQ_DEFAULT_USER', 'guest')}:{os.getenv('RABBITMQ_DEFAULT_PASS', 'guest')}@{os.getenv('RABBITMQ_HOST', 'localhost')}:{os.getenv('RABBITMQ_PORT', '5672')}//"
CELERY_RESULT_BACKEND = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_RESULT_EXPIRES = 60 * 60  # 1 hour
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'
CELERY_TASK_QUEUES = (
    Queue('default', routing_key='default'),
    Queue('content_render', routing_key='content_render'),
    Queue('cache_ops', routing_key='cache_ops'),
)
CELERY_TASK_ROUTES = {
    'content.invalidate_cache': {'queue': 'cache_ops', 'routing_key': 'cache_ops'},
    'content.render_markdown': {'queue': 'content_render', 'routing_key': 'content_render'},
    'content.render_note_markdown': {'queue': 'content_render', 'routing_key': 'content_render'},
    'content.render_podcast_markdown': {'queue': 'content_render', 'routing_key': 'content_render'},
}
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = env_int("CELERY_WORKER_PREFETCH_MULTIPLIER", 1)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

SEARCH_BACKEND = os.getenv('SEARCH_BACKEND', 'database')
MEILISEARCH_URL = os.getenv('MEILISEARCH_URL', '')
MEILISEARCH_API_KEY = os.getenv('MEILISEARCH_API_KEY', '')
MEILISEARCH_INDEX = os.getenv('MEILISEARCH_INDEX', 'content')
ANALYTICS_PROVIDER = os.getenv('ANALYTICS_PROVIDER', '').strip().lower()
ANALYTICS_SITE = os.getenv('ANALYTICS_SITE', '').strip()
ANALYTICS_DASHBOARD_URL = os.getenv('ANALYTICS_DASHBOARD_URL', '').strip()
ANALYTICS_API_BASE_URL = os.getenv('ANALYTICS_API_BASE_URL', '').strip()
ANALYTICS_API_KEY = os.getenv('ANALYTICS_API_KEY', '').strip()
ANALYTICS_API_AUTH_TYPE = os.getenv('ANALYTICS_API_AUTH_TYPE', 'auto').strip().lower()
ANALYTICS_TIMEOUT_SECONDS = env_int('ANALYTICS_TIMEOUT_SECONDS', 5)
HEALTH_CHECK_TOKEN = os.getenv('HEALTH_CHECK_TOKEN', '').strip()
API_ANON_THROTTLE_RATE = os.getenv('API_ANON_THROTTLE_RATE', '120/hour')
API_USER_THROTTLE_RATE = os.getenv('API_USER_THROTTLE_RATE', '600/hour')
API_PUBLIC_CONTENT_THROTTLE_RATE = os.getenv('API_PUBLIC_CONTENT_THROTTLE_RATE', '240/hour')
API_FRIEND_LINK_APPLY_THROTTLE_RATE = os.getenv('API_FRIEND_LINK_APPLY_THROTTLE_RATE', '12/hour')
API_SEARCH_THROTTLE_RATE = os.getenv('API_SEARCH_THROTTLE_RATE', '30/hour')
API_HEALTH_THROTTLE_RATE = os.getenv('API_HEALTH_THROTTLE_RATE', '30/hour')
API_PUBLIC_HEALTH_THROTTLE_RATE = os.getenv('API_PUBLIC_HEALTH_THROTTLE_RATE', '120/hour')


# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': API_ANON_THROTTLE_RATE,
        'user': API_USER_THROTTLE_RATE,
        'public_content': API_PUBLIC_CONTENT_THROTTLE_RATE,
        'friend_link_apply': API_FRIEND_LINK_APPLY_THROTTLE_RATE,
        'search': API_SEARCH_THROTTLE_RATE,
        'health': API_HEALTH_THROTTLE_RATE,
        'health_public': API_PUBLIC_HEALTH_THROTTLE_RATE,
        'health_internal': API_HEALTH_THROTTLE_RATE,
    },
    'EXCEPTION_HANDLER': 'apps.content.api_utils.admin_exception_handler',
    'NUM_PROXIES': env_int("DRF_NUM_PROXIES", 1),
}

if not DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]
REST_FRAMEWORK['DATETIME_FORMAT'] = '%Y-%m-%dT%H:%M:%S%z'
REST_FRAMEWORK['DATE_FORMAT'] = '%Y-%m-%d'

