# Generated by Django 5.0.3 on 2026-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL 友好的唯一标识符", max_length=200, unique=True
                    ),
                ),
                ("title", models.CharField(help_text="文章标题", max_length=500)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("zh", "Chinese")],
                        db_index=True,
                        default="en",
                        help_text="内容语言",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        help_text="发布状态",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="发布时间", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
                ("content_md", models.TextField(help_text="Markdown 源内容")),
                (
                    "content_html",
                    models.TextField(blank=True, help_text="渲染后的 HTML 内容"),
                ),
                (
                    "toc_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="目录结构 JSON"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="文章摘要", max_length=500),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True, help_text="封面图片 URL", max_length=500
                    ),
                ),
                (
                    "reading_time",
                    models.IntegerField(default=0, help_text="预计阅读时长（分钟）"),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"], name="idx_post_status_pub"
                    ),
                    models.Index(
                        fields=["lang", "status", "published_at"],
                        name="idx_post_lang_status_pub",
                    ),
                ],
            },
        ),
    ]
