# Generated by Django 6.0.2 on 2026-03-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("minio", "MinIO"),
                            ("s3", "Amazon S3"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="assets/%Y/%m/")),
                ("object_key", models.CharField(blank=True, max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "assets",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="content_html",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_md",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="lang",
            field=models.CharField(
                choices=[("en", "English"), ("zh", "Chinese")],
                db_index=True,
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="reading_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="toc_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(max_length=500)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("zh", "Chinese")],
                        db_index=True,
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("content_md", models.TextField(blank=True)),
                ("content_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="podcast_covers",
                        to="content.asset",
                    ),
                ),
            ],
            options={
                "db_table": "podcasts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                ("tier", models.CharField(blank=True, db_index=True, max_length=50)),
                ("display_order", models.IntegerField(default=0)),
                ("active_from", models.DateField(blank=True, null=True)),
                ("active_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsor_avatars",
                        to="content.asset",
                    ),
                ),
            ],
            options={
                "db_table": "sponsors",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("repo_url", models.URLField(blank=True, max_length=500)),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("zh", "Chinese")],
                        db_index=True,
                        max_length=2,
                        null=True,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="content.tag"
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="content.tag"
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("caption", models.TextField(blank=True)),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("zh", "Chinese")],
                        db_index=True,
                        max_length=2,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_originals",
                        to="content.asset",
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_thumbnails",
                        to="content.asset",
                    ),
                ),
            ],
            options={
                "db_table": "photos",
                "ordering": ["-taken_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["taken_at"], name="idx_photo_taken_at")
                ],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("zh", "Chinese")],
                        db_index=True,
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_md", models.TextField()),
                ("content_html", models.TextField(blank=True)),
                ("toc_json", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, max_length=500)),
                ("reading_time", models.IntegerField(default=0)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="content.tag"
                    ),
                ),
            ],
            options={
                "db_table": "notes",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"], name="idx_note_status_pub"
                    ),
                    models.Index(
                        fields=["lang", "status", "published_at"],
                        name="idx_note_lang_status_pub",
                    ),
                ],
            },
        ),
    ]
