# Generated by Django 5.2.11 on 2026-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="content_md",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#6b7280", max_length=7),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
