# Generated by Django 5.2.11 on 2026-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_project_content_html_project_content_md_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
