# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120)),
                ('site_url', models.URLField(max_length=500, unique=True)),
                ('logo_url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_note', models.CharField(blank=True, max_length=500)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], db_index=True, default='pending', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'friend_links',
                'ordering': ['display_order', '-reviewed_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='friendlink',
            index=models.Index(fields=['status', 'display_order'], name='idx_friend_link_status_order'),
        ),
        migrations.AddIndex(
            model_name='friendlink',
            index=models.Index(fields=['created_at'], name='idx_friend_link_created_at'),
        ),
    ]
