import { forwardRef, type ChangeEvent } from 'react'
import type { FieldErrors, UseFormRegister } from 'react-hook-form'
import { Input } from '@/components/ui/input'
import { useTranslation } from '@/features/i18n/use-translation'
import type { ProjectFormValues } from '@/features/projects/schema/project-form-schema'

interface ProjectBasicInfoSectionProps {
  errors: FieldErrors<ProjectFormValues>
  register: UseFormRegister<ProjectFormValues>
}

export function ProjectBasicInfoSection({ errors, register }: ProjectBasicInfoSectionProps) {
  const { t } = useTranslation()

  return (
    <div className="space-y-4">
      <Input
        label={t('项目名称', 'Project Name')}
        error={errors.title?.message}
        placeholder={t('请输入项目名称', 'Enter the project name')}
        {...register('title')}
      />
      <Input
        label={t('别名', 'Slug')}
        error={errors.slug?.message}
        placeholder={t('可留空由后端生成', 'Optional. Can be generated by the backend')}
        {...register('slug')}
      />
      <SelectLikeField
        label={t('语言', 'Language')}
        options={[
          { label: t('中文', 'Chinese'), value: 'zh' },
          { label: t('英文', 'English'), value: 'en' },
        ]}
        {...register('lang')}
      />
      <SelectLikeField
        label={t('状态', 'Status')}
        options={[
          { label: t('草稿', 'Draft'), value: 'draft' },
          { label: t('已发布', 'Published'), value: 'published' },
        ]}
        {...register('status')}
      />
      <Input
        label={t('项目简介', 'Project Summary')}
        error={errors.summary?.message}
        placeholder={t('用于列表与预览区的简介文案', 'Used in the list and preview summary')}
        {...register('summary')}
      />
    </div>
  )
}

const SelectLikeField = forwardRef<
  HTMLSelectElement,
  {
    label: string
    options: Array<{ label: string; value: string }>
    value?: string
    onChange?: (event: ChangeEvent<HTMLSelectElement>) => void
    onBlur?: React.FocusEventHandler<HTMLSelectElement>
    name?: string
  }
>(function SelectLikeField({ label, name, onBlur, onChange, options, value }, ref) {
  return (
    <label className="flex flex-col gap-2 text-sm text-text">
      <span className="font-medium">{label}</span>
      <select
        className="h-11 rounded-lg border border-border bg-white/12 px-4 text-sm text-text outline-none transition dark:bg-white/[0.03]"
        name={name}
        onBlur={onBlur}
        onChange={onChange}
        ref={ref}
        value={value}
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  )
})
