import { forwardRef } from 'react'
import type { FieldErrors, UseFormRegister } from 'react-hook-form'
import { Input } from '@/components/ui/input'
import { useTranslation } from '@/features/i18n/use-translation'
import type { PostFormValues } from '@/features/posts/schema/post-form-schema'

interface PostBasicInfoSectionProps {
  errors: FieldErrors<PostFormValues>
  register: UseFormRegister<PostFormValues>
}

export function PostBasicInfoSection({ errors, register }: PostBasicInfoSectionProps) {
  const { t } = useTranslation()

  return (
    <div className="space-y-4">
      <Input
        label={t('标题', 'Title')}
        error={errors.title?.message}
        placeholder={t('请输入文章标题', 'Enter the post title')}
        {...register('title')}
      />
      <Input
        label={t('别名', 'Slug')}
        error={errors.slug?.message}
        placeholder={t('可留空由后端生成', 'Optional. Can be generated by the backend')}
        {...register('slug')}
      />
      <SelectLikeField
        label={t('语言', 'Language')}
        options={[
          { label: t('中文', 'Chinese'), value: 'zh' },
          { label: t('英文', 'English'), value: 'en' },
        ]}
        {...register('lang')}
      />
      <SelectLikeField
        label={t('状态', 'Status')}
        options={[
          { label: t('草稿', 'Draft'), value: 'draft' },
          { label: t('已发布', 'Published'), value: 'published' },
        ]}
        {...register('status')}
      />
      <Input
        label={t('摘要', 'Summary')}
        error={errors.summary?.message}
        placeholder={t('用于列表与详情摘要展示', 'Used in list and detail summary views')}
        {...register('summary')}
      />
    </div>
  )
}

const SelectLikeField = forwardRef<
  HTMLSelectElement,
  {
    label: string
    options: Array<{ label: string; value: string }>
    value?: string
    onChange?: (event: React.ChangeEvent<HTMLSelectElement>) => void
    onBlur?: React.FocusEventHandler<HTMLSelectElement>
    name?: string
  }
>(function SelectLikeField({ label, name, onBlur, onChange, options, value }, ref) {
  return (
    <label className="flex flex-col gap-2 text-sm text-text">
      <span className="text-[13px] font-semibold">{label}</span>
      <select
        className="admin-select h-11 px-4 text-sm"
        name={name}
        onBlur={onBlur}
        onChange={onChange}
        ref={ref}
        value={value}
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  )
})
